# Generated by Django 3.1.7 on 2021-04-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='call_type',
            field=models.CharField(choices=[('Inbound Call', 'Inbound Call'), ('Outbound Call', 'Outbound Call'), ('Inbound Missedcall', 'Inbound Missedcall'), ('Outbound Live Call', 'Outbound Live Call')], max_length=50),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='status',
            field=models.CharField(choices=[('No Response', 'No Response'), ('Unreachable', 'Unreachable'), ('DND', 'DND'), ('Invalid Number', 'Invalid Number'), ('Rejected', 'Rejected'), ('Busy', 'Busy'), ('Answered', 'Answered')], max_length=50),
        ),
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='ivrprompt',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='partnersystemphone',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='parent_type',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Grand Father', 'Grand Father'), ('Grand Mother', 'Grand Mother'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In-Progress', 'In-Progress'), ('Complete', 'Complete')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemphone',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='usermodulecontent',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In-Progress', 'In-Progress'), ('Complete', 'Complete')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprogram',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
    ]
