# Generated by Django 3.1.7 on 2021-04-13 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0002_auto_20210410_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmodule',
            old_name='module',
            new_name='module_id',
        ),
        migrations.RenameField(
            model_name='programmodule',
            old_name='program',
            new_name='program_id',
        ),
    ]
