# Generated by Django 3.1.7 on 2021-04-30 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0003_auto_20210413_2139'),
        ('admindashboard', '0002_auto_20210419_1806'),
    ]

    operations = [
    ]
