# Generated by Django 3.1.7 on 2021-04-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0003_auto_20210413_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmodule',
            old_name='module_id',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='programmodule',
            old_name='program_id',
            new_name='program',
        ),
    ]
