version: "3.9"

services:
  db:
    image: postgres
    ports:
      - 5435:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=rp_ivr_staging
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    hostname: postgres
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate --fake-initial && python manage.py runserver 0.0.0.0:8001"
    container_name: admindashboard
    volumes:
      - .:/admindashboard
    ports:
      - "8001:8001"
    depends_on:
      - db
