version: "3.9"

services:
  db:
    image: postgres
    ports:
      - 80:80
      - 5432:5432
    expose:
      - "5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    hostname: postgres
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    container_name: admindashboard
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - db
